#pragma once

#include <linux/ioctl.h>

#define KMESSAGED_IOC_MAGIC 0x6b
#define KMESSAGED_IOC_RESET _IO(KMESSAGED_IOC_MAGIC, 0)
#define KMESSAGED_IOC_S_RDMOD _IOW(KMESSAGED_IOC_MAGIC, 1, int)
#define KMESSAGED_IOC_RDMOD _IO(KMESSAGED_IOC_MAGIC, 2, int)
#define KMESSAGED_IOC_S_MSGLMT _IOW(KMESSAGED_IOC_MAGIC, 3, int)
#define KMESSAGED_IOC_MSGLMT _IO(KMESSAGED_IOC_MAGIC, 4, int)
#define KMESSAGED_IOC_RMMSG _IOW(KMESSAGED_IOC_MAGIC, 5, char *)
#define KMESSAGED_IOC_MAXNR 5

#define KMESSAGED_EXPORT 

#define KMESSAGED_MAX_USERNAME_LEN 20
#define KMESSAGED_DEFAULT_MESSAGE_LIMIT 20
